# BAF507E Finanacial Database - Week5, #2

## Subject : Exchange Rate Forecasts with Macroeconomic Variables

## 조성은 (ID : 20204150)

## 1. Data Download

### 환율 - krw_usd_xr.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3A036Y001.0000001



### PPP 환율 - krw_usd_ppp_xr.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=WB%3APA.NUS.PPP-KOR



### 경상수지: 한국 - current_account_korea.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3A022Y013.000000



### 경상수지: 미국 - current_account_us.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3AI10Y031.US



### GDP: 한국 - gdp_korea.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3AI10Y042.KOR



### GDP: 미국 - gdp_us.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3AI10Y042.USA



### 경제 성장률: 한국 - gdp_growth_korea.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3A901Y001.AI1AA



### 경제 성장률: 미국 - gdp_growth_us.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3AI10Y041.USA



### 소비자 물가지수: 한국 - cpi_korea.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3AI10Y022.KR



### 소비자 물가지수: 미국 - cpi_us.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3AI10Y022.US



### 1년 국채 금리: 한국 - int_rate_korea.xlsx


https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3A060Y001.010190000



### 1년 국채 금리: 미국 - int_rate_us.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=FRED%3ADGS1



### 한국은행 외환 보유액 - foreign_reserves.xlsx



https://www.deepsearch.com/analytics/economic-indicator?pageView=1&symbol=BOK%3A901Y001.AI1DC

## 2. Data Loading

In [1]:
import pandas as pd # 13개의 파일 쉽게 한번에 로드하는 법

In [30]:
filenames = [
    'krw_usd_xr', 'krw_usd_ppp_xr',
    'current_account_korea', 'current_account_us',
    'gdp_korea', 'gdp_us',
    'gdp_growth_korea', 'gdp_growth_us',
    'cpi_korea', 'cpi_us',
    'int_rate_korea', 'int_rate_us',
    'foreign_reserves',
]

In [31]:
dfs = []

for fname in filenames:   #take a Loof inside the file here
    print('Loading {}'.format(fname))
    
    df = pd.read_excel('{}.xlsx'.format(fname))    # reading the file name
    df['날짜']= pd.to_datetime(df['날짜'])
    df = df.set_index('날짜')
    df.columns = [fname]
    
    if fname in ['gdp_growth_korea', 'gdp_growth_us', 'current_account_us']:   #quarterly basis 분기별 자료 ---> 연간 자료
        df[fname] = df[fname].rolling(4).sum()
    
    if fname in ['current_account_korea']:
        df[fname] = df[fname].rolling(12).sum()    #monthly basis 월별 자료 ---> 연간 자료
    
    dfs.append(df)
    
print('Data loading is completed!!')

Loading krw_usd_xr
Loading krw_usd_ppp_xr
Loading current_account_korea
Loading current_account_us
Loading gdp_korea
Loading gdp_us
Loading gdp_growth_korea
Loading gdp_growth_us
Loading cpi_korea
Loading cpi_us
Loading int_rate_korea
Loading int_rate_us
Loading foreign_reserves
Data loading is completed!!

In [32]:
# concat = concatenate
df_merged = pd.concat(dfs, axis=1)

In [33]:
df_merged = df_merged.resample('M').last()

In [34]:
df_merged = df_merged.fillna(method='ffill')

In [35]:
df_merged.tail()

,krw_usd_xr,krw_usd_ppp_xr,current_account_korea,current_account_us,gdp_korea,gdp_us,gdp_growth_korea,gdp_growth_us,cpi_korea,cpi_us,int_rate_korea,int_rate_us,foreign_reserves
날짜,,,,,,,,,,,,,
2021-01-31,1114.6,860.213997,81585.5,-572256.0,1642183.9,21427700.0,-1.6,-1.7,116.93,119.96,0.670,0.10,442727709.0
2021-02-28,1108.4,860.213997,83252.8,-572256.0,1642183.9,21427700.0,1.3,-1.7,117.52,120.62,0.673,0.08,447557482.0
2021-03-31,1133.5,860.213997,85108.3,-572256.0,1642183.9,21427700.0,1.3,-1.7,117.69,121.47,0.690,0.07,446127385.0
2021-04-30,1107.4,860.213997,85108.3,-572256.0,1642183.9,21427700.0,1.3,-1.7,117.94,121.47,0.642,0.05,446127385.0
2021-05-31,1121.1,860.213997,85108.3,-572256.0,1642183.9,21427700.0,1.3,-1.7,117.94,121.47,0.610,0.05,446127385.0

In [36]:
df_merged.loc['2010-01-01':].head()

,krw_usd_xr,krw_usd_ppp_xr,current_account_korea,current_account_us,gdp_korea,gdp_us,gdp_growth_korea,gdp_growth_us,cpi_korea,cpi_us,int_rate_korea,int_rate_us,foreign_reserves
날짜,,,,,,,,,,,,,
2010-01-31,1156.5,824.618824,31135.4,-372522.0,943941.9,14448932.0,5.1,0.3,98.82,99.37,3.22,0.30,273693584.0
2010-02-28,1158.4,824.618824,25800.0,-372522.0,943941.9,14448932.0,7.0,0.3,99.02,99.40,3.07,0.32,270659721.0
2010-03-31,1130.8,824.618824,20931.1,-382165.0,943941.9,14448932.0,7.0,1.8,99.22,99.81,2.70,0.41,272331061.0
2010-04-30,1115.5,824.618824,18588.8,-382165.0,943941.9,14448932.0,7.0,1.8,99.62,99.98,2.65,0.41,278873477.0
2010-05-31,1200.2,824.618824,22909.8,-382165.0,943941.9,14448932.0,7.6,1.8,99.72,100.06,2.75,0.34,270221038.0

## 3. Compute new columns

### 환율 수익률 (Currency returns)

In [37]:
df_merged['ann_ret'] = df_merged['krw_usd_xr'].pct_change(periods=12) * 100

In [38]:
df_merged['F12.ann_ret'] = df_merged['ann_ret'].shift(-12) # the annual return for 12 months later

### Real XR

In [39]:
df_merged['real_xr'] = df_merged['krw_usd_ppp_xr'] / df_merged['krw_usd_xr']

### GDP대비 경상수지 비율 (Current account relative to GDP)

In [40]:
df_merged['ca_gdp_korea'] = df_merged['current_account_korea'] / df_merged['gdp_korea'] * 100

In [41]:
df_merged['ca_gdp_us'] = df_merged['current_account_us'] / df_merged['gdp_us'] * 100

계산을 하고 나면 항상 외부 소스와 비교를 해보는 건 좋은 습관입니다. 한번 제대로 계산이 되었는지 비교해 볼까요?

In [42]:
df_merged.loc['2019-10-01':][['ca_gdp_korea', 'ca_gdp_us']].head()

            ca_gdp_korea  ca_gdp_us
날짜
2019-10-31      3.470373  -2.601153
2019-11-30      3.519438  -2.601153
2019-12-31      3.651917  -2.325728
2020-01-31      3.512475  -2.325728
2020-02-29      3.665722  -2.325728

### Current account to GDP Ratio : Korea
https://www.statista.com/statistics/642265/south-korea-current-account-percentage-gdp/

### Current account to GDP Ratio : US
https://tradingeconomics.com/united-states/current-account-to-gdp